// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./components/scrollbar/src/bar.vue')['default']
    Scrollbar: typeof import('./components/scrollbar/src/scrollbar.vue')['default']
    Thumb: typeof import('./components/scrollbar/src/thumb.vue')['default']
  }
}

export { }
